# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'Carpool Karaoke' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Carpool Karaoke
  pod 'Firebase/Core' 
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
end
